### ISSUE TITLE
Gather feedback from users

### ISSUE THREAD

**Issue by jacoscaz** [beautifulinteractions/node-quadstore#18]
- @dmitrizagidulin
- @bigbluehat
- @jmatsushita
- @elf-pavlik

**Comment by dmitrizagidulin** [comment]
Happy to! I'll try wiring it up to rdflib and play around with it.

Couple of quick comments:

1. maybe the `delput()` and `getdelput()` are better named `patch()`? The SPARQL patch interface is intended exactly for that use case -- a specification of quads to delete and quads to insert.
2. The [RDF/JS interface for Quad](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#quad) uses `graph` as the 4th property of a term, and it looks like you're using `context` for the same property. Will you also support `graph` as an alias for `context`?

**Comment by dmitrizagidulin** [comment]
References for the `patch()` comment:

* [TurtlePatch Proposal](https://www.w3.org/2001/sw/wiki/TurtlePatch), note the two `DELETE WHERE` and `INSERT DATA` sections. (This is equivalent semantics to your `getdelput()` method.)
* [SPARQL 1.1 Update recommendation](https://www.w3.org/TR/sparql11-update/#graphUpdate), specifically meant for RDF Graph Stores. The main difference from the Turtle Patch proposal is that instead of `DELETE WHERE`, this spec uses `DELETE DATA` -- they don't allow querying for deleted quads, they want them to be listed explicitly. (This is equivalent semantics to your `delput()` method.)

Proposed API change:

`.patch(Array|Object delete, Array insert)`

If `delete` is of type `Array`, treat it as `DELETE DATA` (explicit list of quads to delete), and if `delete` is of type `Object`, treat it as `DELETE WHERE` (like `getdelput` currently does).

**Comment by jacoscaz** [comment]
Wonderful suggestion. Thank you! I'll open an issue straight away. With regards to point 2), if you are using the QuadStore class the name of the context term can be configured via this option: `new QuadStore({ contextKey: 'graph' });`

**Comment by dmitrizagidulin** [comment]
Ah, nice (re `contextKey`). 

Any reason to not just use `graph`, tho? (Or maybe see if you can get the RDF/JS spec to change to `context`, if you prefer that one?)

**Comment by jacoscaz** [comment]
Not really on our part. While researching we realised that a quadstore could also be used outside the RDF world and that some libraries were using different keywords for the fourth term, hence our decision to make that configurable (and to implement support for the RDF/JS interface in a dedicated class).

**Comment by dmitrizagidulin** [comment]
No prob, makes sense.

(It's probably worth mentioning `contextKey` in the README / docs, then.)

**Comment by elf-pavlik** [comment]
It looks like RdfStore sets it correctly
https://github.com/beautifulinteractions/node-quadstore/blob/master/lib/rdfstore.js#L20
```js
opts.contextKey = 'graph';
```

**Comment by jacoscaz** [comment]
In case anyone is still following this, `7.0.1-alpha.9` brings SPARQL support, including SPARQL/1.1 DELETE/INSERT WHERE. I'll close this issue as it's been open for way too long without much activity. I've also applied for the beta of the upcoming "discussions" feature here on GH for more brainstorm-y feedback.
