### ISSUE TITLE
Add browser support

### ISSUE THREAD

**Issue by elf-pavlik** [beautifulinteractions/node-quadstore#4]
LevelGraph works in node.js as well as in web browsers, does node-quadstore also work in web browsers?

**Comment by jacoscaz** [comment]
Untested and I suspect we need to pass options from our constructor to leveldb's but node-quadstore should work in web browsers just fine.

**Comment by jacoscaz** [comment]
See https://github.com/maxogden/level.js/blob/master/test/test-levelup.js - this might already work.

**Comment by elf-pavlik** [comment]
In LevelGraph one needs to require leveljs, create factory using it and pass it to levelup
https://github.com/mcollina/levelgraph#browserify

I think you may need to adjust how you call levelup https://github.com/beautifulinteractions/node-quadstore/blob/82ecfdb6bffe47e5eb59cbc512202bb788715555/index.js#L137

**Comment by elf-pavlik** [comment]
I remember LevelGraph using https://www.npmjs.com/package/zuul to run tests in a browser as well as test it cross browser using SauceLabs

**Comment by jacoscaz** [comment]
@elf-pavlik we have no use for this but we're open to work on it if the community is interested. Would it be worth the effort? Is there anyone who'd be willing to help? There's a lot to figure out for this.

**Comment by jacoscaz** [comment]
@elf-pavlik is this something the community might still be interested in?

**Comment by jacoscaz** [comment]
Revisiting this issue as we might have a use case for having an in-browser quadstore. What is needed for this?

- [ ] eliminate node-only dependencies
    - [ ] extract http layer and repackage into separate npm package
- [ ] transform ES6 / ES7 syntax to ES5
- [ ] create browser bundle
- [ ] add level.js to the tested backends
- [ ] run level.js tests in-browser

The bundle will doubtlessly become quite big, mostly due to the amount of dependencies involved (especially `@comunica/actor-init-sparql-rdfjs`). We'll see what to do about that when we get there.

**Comment by jacoscaz** [comment]
Done in v5.0.2!
