### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by jmatsushita** [beautifulinteractions/node-quadstore#47]
Hi there!

It would be nice to have loading and querying benchmarks like [dgraph vs neo4j](https://docs.dgraph.io/performance/) or [dgraph vs cayley](https://github.com/ankurayadav/graphdb-benchmarks).

Any approach you'd prefer?

Jun

**Comment by jacoscaz** [comment]
Hello Jun.

Yes, benchmarks are very much something I'd like to introduce. I have yet to think about a suitable approach, though. What are the questions you would like to be answered by a benchmark suite?

**Comment by jmatsushita** [comment]
Hi Jacopo,

I'm thinking load time with the streaming interface (with the N3.js reader) for the [21million.rdf](https://github.com/ankurayadav/graphdb-benchmarks/tree/master/data) file. And then an equivalent query to [this one](https://github.com/ankurayadav/graphdb-benchmarks/blob/master/dgraph/queries.go#L31-L46).

That would make things _somewhat_ comparable at least with cayley and dgraph which I find interesting to compare with.

Cheers,

Jun

**Comment by jacoscaz** [comment]
It's been some time! In the unlikely case that anyone is still following in this, I've been working on a few benchmarks in the `src/perf` folder. Instead of focusing on specific queries, of which I would need hundreds to have benchmark one could rely upon, I've been focusing on specific metrics:

- imported quads per second (15k quad/second, see `src/perf/loadfile.ts`)
- join operations per second (3.4k join/second, see `src/perf/search.ts`)

I will close this issue, which has been around for way too long, and will open new ones specific to this or that metric, according to how the project evolves.
